var allFuntions = require("./funtions");
console.log(allFuntions.multiplos(4, 2));
console.log(allFuntions.multiplos(28, 18));
console.log(allFuntions.greatest(3423, 234235));
console.log(allFuntions.greatest(234235, 234235));
console.log(allFuntions.greatest(-343, 0));
console.log(allFuntions.greatest(-1, 0));
console.log(allFuntions.ifNum(345));
console.log(allFuntions.ifNum(0));
console.log(allFuntions.ifNum(-123));
console.log(allFuntions.ifNum(-123.23));
console.log(allFuntions.strLength("carlosEnrique"));
console.log(allFuntions.strLength("patos"));
console.log(allFuntions.strLength("og"));
console.log(allFuntions.promNum(3, 5, 6));
console.log(allFuntions.promNum(5, 5, 6));
console.log(allFuntions.promNum(-5, -5, 6));
console.log(allFuntions.promNum(8, 8, 1));
